package agent

// The prompt corpus under docs/prompt-inventory/ is the one view of every
// model-facing string (generated by scripts/extract-prompt-inventory.py, and
// kept honest by the `prompt-inventory` CI job). Reading it as a corpus — not as
// individual files — is what lets one test cover rules that used to need one
// test per call site.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The five r39–r45 incidents all came from the same hand-rolled shape: a
// detached start written by hand, whose output the next call had to guess at.
// run_in_background is the only supported way to wait now, so the corpus must not
// teach the old vocabulary anywhere — a hint that mentions `nohup` or
// `</dev/null` re-opens the door the refusal closes.
func TestPromptCorpusTeachesNoHandRolledWaits(t *testing.T) {
	files, err := filepath.Glob(filepath.Join("..", "..", "docs", "prompt-inventory", "*.md"))
	if err != nil {
		t.Fatalf("glob: %v", err)
	}
	if len(files) == 0 {
		t.Fatal("no prompt snapshot found — run scripts/extract-prompt-inventory.py")
	}

	banned := []string{"nohup", "</dev/null", "setsid", "tmux"}
	for _, path := range files {
		body, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		for _, needle := range banned {
			if idx := strings.Index(strings.ToLower(string(body)), needle); idx >= 0 {
				line := 1 + strings.Count(string(body[:idx]), "\n")
				t.Errorf("%s:%d mentions %q — waiting belongs on run_in_background only",
					filepath.Base(path), line, needle)
			}
		}
	}
}

// A rule that lives in two places is paid for twice on every request, and the two
// copies drift. The file-delivery rule (write binary output into the workspace,
// reference it by path, never inline base64) belongs to the system prompt; the
// tool SCHEMA must not restate it. Within the system prompt several sandbox
// sections touch it, which is one owner, not four.
func TestToolDescriptionsDoNotRestateTheDeliveryRule(t *testing.T) {
	if got := blocksContainingIn(t, "c-tool-descriptions.md", "base64"); len(got) > 0 {
		t.Fatalf("a tool description restates the delivery rule: %v", got)
	}
	if got := blocksContainingIn(t, "a-system-prompt.md", "base64"); len(got) == 0 {
		t.Fatal("the delivery rule vanished from the system prompt — it must have exactly one home")
	}
}

// todo.md's operational rules (write it once per turn, flip items with edit_file,
// bare filename) are load-bearing: the chat panel re-fetches on every write that
// touches the file and hides itself when the file is empty
// (web/src/components/chat-screen.tsx:517-525). They live in the task-delegation
// module; the plan-mode nudge used to repeat the "first action" line, which is the
// part nobody needs twice.
func TestTodoRulesHaveOneOwner(t *testing.T) {
	owners := blocksContaining(t, "Never call")
	if len(owners) != 1 || !strings.HasPrefix(owners[0], "a-system-prompt.md") {
		t.Fatalf("the todo.md operational rules must live in one system-prompt block, found: %v", owners)
	}
	// The plan-mode nudge used to repeat the "first action writes todo.md" line.
	// It is plan-mode-only, so the repetition is cheap in tokens but expensive in
	// drift: two statements of one rule, updated separately.
	if strings.Contains(planModeNudge(), "todo.md") {
		t.Fatal("planModeNudge restates the todo.md rule that the system prompt already carries")
	}
}

// blocksContaining returns "<file>:<block name>" for every extracted block whose
// text contains needle (case-insensitive).
func blocksContaining(t *testing.T, needle string) []string {
	t.Helper()
	files, err := filepath.Glob(filepath.Join("..", "..", "docs", "prompt-inventory", "*.md"))
	if err != nil {
		t.Fatalf("glob: %v", err)
	}
	var out []string
	for _, path := range files {
		out = append(out, scanBlocks(t, path, needle)...)
	}
	return out
}

func blocksContainingIn(t *testing.T, name, needle string) []string {
	t.Helper()
	return scanBlocks(t, filepath.Join("..", "..", "docs", "prompt-inventory", name), needle)
}

func scanBlocks(t *testing.T, path, needle string) []string {
	t.Helper()
	var out []string
	{
		body, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		block := ""
		for _, line := range strings.Split(string(body), "\n") {
			if strings.HasPrefix(line, "## ") {
				block = strings.TrimSpace(strings.TrimPrefix(line, "## "))
				continue
			}
			if strings.Contains(strings.ToLower(line), strings.ToLower(needle)) {
				out = append(out, filepath.Base(path)+":"+block)
			}
		}
	}
	return out
}
