package agent

// The prompt corpus under docs/prompt-inventory/ is the one view of every
// model-facing string (generated by scripts/extract-prompt-inventory.py, and
// kept honest by the `prompt-inventory` CI job). Reading it as a corpus — not as
// individual files — is what lets one test cover rules that used to need one
// test per call site.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The five r39–r45 incidents all came from the same hand-rolled shape: a
// detached start written by hand, whose output the next call had to guess at.
// run_in_background is the only supported way to wait now, so the corpus must not
// teach the old vocabulary anywhere — a hint that mentions `nohup` or
// `</dev/null` re-opens the door the refusal closes.
func TestPromptCorpusTeachesNoHandRolledWaits(t *testing.T) {
	files, err := filepath.Glob(filepath.Join("..", "..", "docs", "prompt-inventory", "*.md"))
	if err != nil {
		t.Fatalf("glob: %v", err)
	}
	if len(files) == 0 {
		t.Fatal("no prompt snapshot found — run scripts/extract-prompt-inventory.py")
	}

	banned := []string{"nohup", "</dev/null", "setsid", "tmux"}
	for _, path := range files {
		body, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		for _, needle := range banned {
			if idx := strings.Index(strings.ToLower(string(body)), needle); idx >= 0 {
				line := 1 + strings.Count(string(body[:idx]), "\n")
				t.Errorf("%s:%d mentions %q — waiting belongs on run_in_background only",
					filepath.Base(path), line, needle)
			}
		}
	}
}
